{% set name = "fastobo" %}
{% set version = "0.13.0" %}

package:
  name: "{{ name | lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: "c4548bcfb7f9f87188bf5d8e4c7fd530162707265a8d644ee75259d305cd6964"

build:
  number: 0
  script: 
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler("rust") }}
    - cargo-bundle-licenses
  host:
    - python
    - pip
    - maturin >=1,<2
  run:
    - python

test:
  imports:
    - fastobo

about:
  home: "https://github.com/fastobo/fastobo-py"
  license: "MIT"
  license_family: "MIT"
  license_file: 
    - COPYING
    - THIRDPARTY.yml
  summary: "Faultless AST for Open Biomedical Ontologies in Python"
  doc_url: "https://fastobo.readthedocs.io"

extra:
  recipe-maintainers:
    - althonos
